USE_CAMERA_STUB := false

# inherit from the proprietary version
-include vendor/lge/p350/BoardConfigVendor.mk

# Camera
TARGET_DISABLE_ARM_PIE := true
BOARD_NEEDS_MEMORYHEAPPMEM := true
BOARD_USE_NASTY_PTHREAD_CREATE_HACK := true
# BOARD_CAMERA_USE_GETBUFFERINFO := true
# BOARD_USE_CAF_LIBCAMERA := true
TARGET_NO_HW_VSYNC := true
BOARD_USE_FROYO_LIBCAMERA := true

# CPU & Platform
TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true
TARGET_BOARD_PLATFORM := msm7k
TARGET_ARCH_VARIANT := armv6-vfp
ARCH_ARM_HAVE_VFP := true
TARGET_CPU_ABI := armeabi-v6l
TARGET_CPU_ABI2 := armeabi
TARGET_BOOTLOADER_BOARD_NAME := p350
TARGET_OTA_ASSERT_DEVICE := pecan,p350
TARGET_BOARD_PLATFORM_GPU := qcom-adreno200

# Kernel
TARGET_KERNEL_SOURCE := kernel/lge/p350
TARGET_KERNEL_CONFIG := team_kernel_defconfig
BOARD_KERNEL_CMDLINE := mem=215M console=ttyMSM2,115200n8 androidboot.hardware=pecan
BOARD_KERNEL_BASE := 0x02808000
BOARD_KERNEL_PAGESIZE := 2048

# fix this up by examining /proc/mtd on a running device
BOARD_BOOTIMAGE_PARTITION_SIZE := 0x00440000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x00600000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x0c800000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x0bd80000
BOARD_FLASH_BLOCK_SIZE := 131072

TARGET_LIBAGL_USE_GRALLOC_COPYBITS := true
BOARD_USE_NASTY_PTHREAD_CREATE_HACK := true
BOARD_USE_SKIA_LCDTEXT := true
BOARD_USE_ADRENO_200_GPU := true
TARGET_USES_C2D_COMPOSITION := false
BOARD_AVOID_DRAW_TEXTURE_EXTENSION := true
TARGET_USES_GENLOCK := true
BOARD_EGL_CFG := device/lge/p350/configs/egl.cfg

# recovery and bootanimation
BOARD_HAS_NO_SELECT_BUTTON := true
BOARD_NO_RGBX_8888 := true
BOARD_LDPI_RECOVERY := true
BOARD_HAS_JANKY_BACKBUFFER := true
BOARD_USE_CUSTOM_RECOVERY_FONT := '"font_7x16.h"'
TARGET_BOOTANIMATION_PRELOAD := true
TARGET_BOOTANIMATION_USE_RGB565 := true
TARGET_BOOTANIMATION_TEXTURE_CACHE := true

# CFLAGS
COMMON_GLOBAL_CFLAGS += -DNO_RGBX_8888
COMMON_GLOBAL_CFLAGS += -DREFRESH_RATE=60
COMMON_GLOBAL_CFLAGS += -DFORCE_CPU_UPLOAD
COMMON_GLOBAL_CFLAGS += -DFROYO_LIBCAMERA
COMMON_GLOBAL_CFLAGS += -DBINDER_COMPAT
COMMON_GLOBAL_CFLAGS += -DQCOM_ICS_COMPAT

TARGET_SPECIFIC_HEADER_PATH := device/lge/p350/include

TARGET_PROVIDES_LIBLIGHTS := true

# Audio and Bluetooth
TARGET_PROVIDES_LIBAUDIO := true
BOARD_USES_ICS_LIBAUDIO := true
BOARD_USES_AUDIO_LEGACY := false
BOARD_COMBO_DEVICE_SUPPORTED := true
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_BCM := true

# RIL
BOARD_PROVIDES_LIBRIL := true

# USB mass storage
BOARD_USE_USB_MASS_STORAGE_SWITCH := true
TARGET_USE_CUSTOM_LUN_FILE_PATH := /sys/devices/platform/msm_hsusb/gadget/lun0/file
BOARD_UMS_LUNFILE := /sys/devices/platform/msm_hsusb/gadget/lun0/file

# Wi-Fi & Wi-Fi HotSpot
WPA_SUPPLICANT_VERSION          := VER_0_6_X
BOARD_WLAN_DEVICE               := bcm4329
BOARD_WEXT_NO_COMBO_SCAN        := true
BOARD_WPA_SUPPLICANT_DRIVER     := WEXT
WIFI_DRIVER_HAS_LGE_SOFTAP      := true
WIFI_DRIVER_MODULE_PATH         := "/system/lib/modules/wireless.ko"
WIFI_DRIVER_MODULE_ARG          := "firmware_path=/etc/wl/rtecdc.bin nvram_path=/etc/wl/nvram.txt config_path=/data/misc/wifi/config"
WIFI_DRIVER_MODULE_NAME         := "wireless"
WIFI_DRIVER_FW_PATH_STA         := "/system/etc/wl/rtecdc.bin"
WIFI_DRIVER_FW_PATH_AP          := "/system/etc/wl/rtecdc-apsta.bin"

# Browser
JS_ENGINE := v8
HTTP := chrome
WITH_JIT := true
ENABLE_JSC_JIT := true
ENABLE_WEBGL := true
TARGET_FORCE_CPU_UPLOAD := true

# Touch screen compatibility for newer android versions
BOARD_USE_LEGACY_TOUCHSCREEN := true
